name: NodeJS with Yarn

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install # will run `yarn install` command
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed
    - name: Build
      uses: borales/actions-yarn@v4
      with:
        cmd: build # will run `yarn build` command
    - uses: actions/upload-artifact@v3
      with:
        name: Build
        path: dist/
